### ISSUE TITLE
Display errors

### ISSUE THREAD

**Issue by cmalard** [tlvince/validate-commit-msg-bot#1]
Hello there, nice work :beers:

Would it be possible to add in the PR some details about what's wrong ? :-)

**Comment by tlvince** [comment]
Right now, we get something like the following out of `validate-commit-msg`:

```js
const isValid = require('validate-commit-msg')
isValid('foo\n\nbar')
//=> INVALID COMMIT MSG: does not match "<type>(<scope>): <subject>" !                     
//=> foo
//=> false
```

... which I didn't deem particularly useful. What do you think?

**Comment by cmalard** [comment]
For this type of test where the whole RegEx doesn't match sure, but it would be more useful with a commit message like:
```
INVALID COMMIT MSG: "feats" is not allowed type ! Valid types are: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert
feats(scope): tadaaa
```

**Comment by tlvince** [comment]
Much better. Would you like to have a go at it? [validate-commit-msg](https://github.com/conventional-changelog/validate-commit-msg)'s `helpMessage` option looks appropriate.

**Comment by cmalard** [comment]
This is the default error message with this type of message :-)

**Comment by tlvince** [comment]
Doesn't seem to be for me:

```
❯ npm i validate-commit-msg
+ validate-commit-msg@2.14.0
added 7 packages in 1.058s

❯ node
> require('validate-commit-msg')('foo')
INVALID COMMIT MSG: does not match "<type>(<scope>): <subject>" !
foo
false
```

**Comment by cmalard** [comment]
Of course, this message does not validate the RegEx.
Try `feats(scope): tadaaa`

**Comment by tlvince** [comment]
This is implemented in https://github.com/ahmed-taj/commitlint-bot. I'm considering validate-commit-msg-bot deprecated in favour of commitlint-bot. Thanks!
